
# Data loading parameters
data:
  path: "//tempory/ADEChallengeData2016"
  load_width: 128
  load_height: 128
  nb_classes: 151 # 150 object classes, 1 "other" class
  class_weights: "src/class_weights_tmp.pt"

# Architecture parameters
latent_dim: 64
generator_params:
  hidden_dims:
    - 1024
    - 512
    - 256
    - 128
    - 64
discriminator_params:
  down_dims:
    - 3
    - 128
    - 128
    - 256
    - 256
    - 512
    - 512
  up_dims:
    - 256
    - 512
    - 256
    - 256
    - 128
    - 128
    - 64

# Training Parameters
batch_size: 16
optim:
  beta1: 0
  beta2: 0.999
  lr_D: 0.0004
  lr_G: 0.0001
lambda_lm: 5
device: "cuda:0"
epochs: 1 #200
seed: 4
EMA_decay: 0.9999
nb_examples: 8 # must be < batch_size
freq_save: 5 # every 5 epochs

# Tensorboard
tb_folder: "XP"

# Checkpoints
checkpoint_path: "checkpoints"